/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demographic.quanlynhankhauhokhau.suaxoaform;

import demographic.dbConnector.Connector;
import demographic.models.HoKhau;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import demographic.quanlynhankhauhokhau.themform.ThemNhanKhauForm;
import demographic.quanlynhankhauhokhau.themform.ThemNhanKhauForm;
import demographic.models.NhanKhau;


/**
 *
 * @author Nam
 */
public class SuaXoaHoKhauForm extends javax.swing.JFrame {
    
    HoKhau hoKhau;
    
    NhanKhau nhanKhau;
    
    String key = "";

    /**
     * Creates new form Form
     */
    public SuaXoaHoKhauForm() {
        initComponents();
    }
    
    public SuaXoaHoKhauForm(HoKhau hoKhau){
        initComponents();
        this.hoKhau = hoKhau;
        displayTextFields();
        System.out.println(this.hoKhau.toString());
        displayNhanKhau();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuaXoaHoKhau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfSoHoKhau = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNgayLap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbLaChungCu = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tNhanKhau = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfSoCMND = new javax.swing.JTextField();
        tfTenChuHo = new javax.swing.JTextField();
        btnHoanTac = new javax.swing.JButton();
        btnThemNhanKhau = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSuaNhanKhau = new javax.swing.JButton();
        btnTachHoKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelSuaXoaHoKhau.setBackground(new java.awt.Color(255, 255, 255));
        PanelSuaXoaHoKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        PanelSuaXoaHoKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSuaXoaHoKhauMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN HỘ KHẨU CƠ BẢN");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Số hộ khẩu");

        tfSoHoKhau.setForeground(new java.awt.Color(0, 102, 102));
        tfSoHoKhau.setCaretColor(new java.awt.Color(0, 102, 102));
        tfSoHoKhau.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfSoHoKhau.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfSoHoKhau.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfSoHoKhau.setSelectionColor(new java.awt.Color(0, 102, 102));

        tfDiaChi.setForeground(new java.awt.Color(0, 102, 102));
        tfDiaChi.setCaretColor(new java.awt.Color(0, 102, 102));
        tfDiaChi.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfDiaChi.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfDiaChi.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfDiaChi.setSelectionColor(new java.awt.Color(0, 102, 102));
        tfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiaChiActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Địa chỉ");

        tfNgayLap.setForeground(new java.awt.Color(0, 102, 102));
        tfNgayLap.setCaretColor(new java.awt.Color(0, 102, 102));
        tfNgayLap.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfNgayLap.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfNgayLap.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfNgayLap.setSelectionColor(new java.awt.Color(0, 102, 102));

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Ngày lập");

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Là chung cư");

        cbLaChungCu.setForeground(new java.awt.Color(0, 102, 102));
        cbLaChungCu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không", "Có" }));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel21.setBackground(new java.awt.Color(0, 102, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Thông tin nhân khẩu của hộ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        tNhanKhau.setForeground(new java.awt.Color(0, 102, 102));
        tNhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tNhanKhau.setGridColor(new java.awt.Color(188, 206, 206));
        tNhanKhau.setRowHeight(26);
        tNhanKhau.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tNhanKhau.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tNhanKhau.setShowGrid(true);
        tNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNhanKhauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tNhanKhau);

        btnLuu.setBackground(new java.awt.Color(0, 51, 51));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.setMargin(new java.awt.Insets(4, 10, 4, 10));
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 0, 0));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa hộ khẩu");
        btnXoa.setMargin(new java.awt.Insets(4, 10, 4, 10));
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Tên chủ hộ");

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Số CMND");

        tfSoCMND.setForeground(new java.awt.Color(0, 102, 102));
        tfSoCMND.setCaretColor(new java.awt.Color(0, 102, 102));
        tfSoCMND.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfSoCMND.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfSoCMND.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfSoCMND.setSelectionColor(new java.awt.Color(0, 102, 102));
        tfSoCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoCMNDActionPerformed(evt);
            }
        });

        tfTenChuHo.setForeground(new java.awt.Color(0, 102, 102));
        tfTenChuHo.setCaretColor(new java.awt.Color(0, 102, 102));
        tfTenChuHo.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfTenChuHo.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfTenChuHo.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfTenChuHo.setSelectionColor(new java.awt.Color(0, 102, 102));
        tfTenChuHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenChuHoActionPerformed(evt);
            }
        });

        btnHoanTac.setBackground(new java.awt.Color(0, 51, 51));
        btnHoanTac.setForeground(new java.awt.Color(255, 255, 255));
        btnHoanTac.setText("Hoàn tác");
        btnHoanTac.setMargin(new java.awt.Insets(4, 10, 4, 10));
        btnHoanTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoanTacMouseClicked(evt);
            }
        });
        btnHoanTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanTacActionPerformed(evt);
            }
        });

        btnThemNhanKhau.setBackground(new java.awt.Color(0, 51, 51));
        btnThemNhanKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhanKhau.setText("Thêm nhân khẩu");
        btnThemNhanKhau.setMargin(new java.awt.Insets(4, 10, 4, 10));
        btnThemNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemNhanKhauMouseClicked(evt);
            }
        });
        btnThemNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanKhauActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(102, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("THOÁT");
        btnThoat.setBorderPainted(false);
        btnThoat.setMargin(new java.awt.Insets(4, 10, 4, 10));
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnSuaNhanKhau.setBackground(new java.awt.Color(0, 51, 51));
        btnSuaNhanKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaNhanKhau.setText("Sửa nhân khẩu");
        btnSuaNhanKhau.setMargin(new java.awt.Insets(4, 5, 4, 5));
        btnSuaNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNhanKhauMouseClicked(evt);
            }
        });
        btnSuaNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhanKhauActionPerformed(evt);
            }
        });

        btnTachHoKhau.setBackground(new java.awt.Color(102, 102, 0));
        btnTachHoKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnTachHoKhau.setText("Tách hộ khẩu");
        btnTachHoKhau.setMargin(new java.awt.Insets(4, 6, 4, 6));
        btnTachHoKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTachHoKhauMouseClicked(evt);
            }
        });
        btnTachHoKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTachHoKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSuaXoaHoKhauLayout = new javax.swing.GroupLayout(PanelSuaXoaHoKhau);
        PanelSuaXoaHoKhau.setLayout(PanelSuaXoaHoKhauLayout);
        PanelSuaXoaHoKhauLayout.setHorizontalGroup(
            PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuaXoaHoKhauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuaXoaHoKhauLayout.createSequentialGroup()
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSoHoKhau)
                            .addComponent(tfDiaChi)
                            .addComponent(tfNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbLaChungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuaXoaHoKhauLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuaXoaHoKhauLayout.createSequentialGroup()
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHoanTac, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemNhanKhau)
                .addGap(18, 18, 18)
                .addComponent(btnSuaNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTachHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        PanelSuaXoaHoKhauLayout.setVerticalGroup(
            PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfSoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cbLaChungCu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnLuu)
                    .addComponent(btnThemNhanKhau)
                    .addComponent(btnHoanTac)
                    .addComponent(btnSuaNhanKhau)
                    .addComponent(btnTachHoKhau))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelSuaXoaHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelSuaXoaHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiaChiActionPerformed

    private void tNhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNhanKhauMouseClicked
//        displayNhanKhau();
        DefaultTableModel model = (DefaultTableModel)tNhanKhau.getModel();
        int indexRow = tNhanKhau.getSelectedRow();
        key = String.valueOf(model.getValueAt(indexRow, 0).toString());
        try {
            Connection conn = Connector.getConnection();
            String query = "SELECT * FROM nhan_khau where nhan_khau_id = " + key + ";";
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            NhanKhau nhanKhauMoi = new NhanKhau();
            while (resultSet.next()) {
                nhanKhauMoi.setNhanKhauId(resultSet.getInt("nhan_khau_id"));
                nhanKhauMoi.setHoTen(resultSet.getString("ho_ten"));
                nhanKhauMoi.setBietDanh(resultSet.getString("biet_danh"));
                nhanKhauMoi.setGioiTinh(resultSet.getString("gioi_tinh"));
                nhanKhauMoi.setNgaySinh(resultSet.getString("ngay_sinh"));
                nhanKhauMoi.setSoCMND(resultSet.getString("so_CMND"));
                nhanKhauMoi.setNgayCapCMND(resultSet.getString("ngay_cap_CMND"));
                nhanKhauMoi.setNoiCapCMND(resultSet.getString("noi_cap_CMND"));
                nhanKhauMoi.setNoiSinh(resultSet.getString("noi_sinh"));
                nhanKhauMoi.setNguyenQuan(resultSet.getString("nguyen_quan"));
                nhanKhauMoi.setDanToc(resultSet.getString("dan_toc"));
                nhanKhauMoi.setNgheNghiep(resultSet.getString("nghe_nghiep"));
                nhanKhauMoi.setNoiLamViec(resultSet.getString("noi_lam_viec"));
                nhanKhauMoi.setQuanHeVoiChuHo(resultSet.getString("quan_he_voi_chu_ho"));
                nhanKhauMoi.setNgayDangKyThuongTru(resultSet.getString("ngay_dang_ky_thuong_tru"));
                nhanKhauMoi.setDiaChiTruocKhiChuyen(resultSet.getString("dia_chi_truoc_khi_chuyen"));
                nhanKhauMoi.setChuyenDi(resultSet.getString("chuyen_di"));
                nhanKhauMoi.setDeleted(resultSet.getInt("deleted"));
                nhanKhauMoi.setSoHoKhau(resultSet.getString("so_ho_khau"));
                nhanKhauMoi.setQuaDoi(resultSet.getString("qua_doi"));
            }
            nhanKhau = nhanKhauMoi;
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu");
        }
    }//GEN-LAST:event_tNhanKhauMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tfSoCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoCMNDActionPerformed

    private void tfTenChuHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenChuHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenChuHoActionPerformed

    private void btnHoanTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanTacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoanTacActionPerformed

    private boolean checkSoCMNDHoTen(){
        try {
            conn = Connector.getConnection();
            String hoTen = tfTenChuHo.getText();
            String soCMND = tfSoCMND.getText();
            String soHoKhau = hoKhau.getSoHoKhau();
            String sql = "SELECT * FROM nhan_khau "
                    + "WHERE ho_ten = '" + hoTen + "' "
                    + "AND so_CMND = '" + soCMND + "' "
                    + "AND so_ho_khau = '"+ soHoKhau+ "'";
            System.out.println(sql);
            PreparedStatement add = conn.prepareStatement(sql);
            ResultSet rset = add.executeQuery();
            System.out.println(rset.getRow());

            if(rset.next()) {
                return true;
            }
            return false;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối tới cơ sở dữ liệu");
            Logger.getLogger(SuaXoaHoKhauForm.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }

    } 
    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        if (tfSoHoKhau.getText().isEmpty() ||
                tfDiaChi.getText().isEmpty() ||
                tfNgayLap.getText().isEmpty() ||
                tfTenChuHo.getText().isEmpty() ||
                tfSoCMND.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin");
        } 
        else if (checkSoCMNDHoTen() == false){
            JOptionPane.showMessageDialog(this, "Thông tin về chủ hộ có thể chưa chính xác.\n"
                        + "Lưu ý, chủ hộ mới phải là một nhân khẩu trong hộ.");
        }
        else {
            try {
                conn = Connector.getConnection();
                String sql = "UPDATE ho_khau "
                        + "SET so_ho_khau = '" + tfSoHoKhau.getText() + "' ,\n "
                        + "dia_chi = '" + tfDiaChi.getText() + "',\n "
                        + "ngay_lap = '"+ tfNgayLap.getText() + "',\n "
                        + "chu_ho_CMND = '" + tfSoCMND.getText() + "',\n "
                        + "la_chung_cu = '"+ cbLaChungCu.getSelectedItem() + "',\n "
                        + "chu_ho_id = (\n" +
                        "    SELECT nhan_khau_id\n" +
                        "    FROM nhan_khau\n" +
                        "    WHERE so_CMND = '" + tfSoCMND.getText() + "')\n "
                        + "WHERE ho_khau_id = " + hoKhau.getHoKhauId() + ";"; 
                PreparedStatement add = conn.prepareStatement(sql);
//                System.out.println(sql);
                int row = add.executeUpdate();
                
//                sql = "INSERT INTO ho_khau_log(ho_khau_id, so_ho_khau, chu_ho_id, chu_ho_CMND, dia_chi, la_chung_cu, ngay_lap) "
//                        + "VALUES ("
//                        + hoKhau.getHoKhauId()+  ",\n "
//                        + "'" + tfSoHoKhau.getText() + "',\n "
//                        + "(\n" +
//                        "    SELECT nhan_khau_id\n" +
//                        "    FROM nhan_khau\n" +
//                        "    WHERE so_CMND = '" + tfSoCMND.getText() + "'),\n "
//                        + "'" + tfSoCMND.getText() + "',\n "
//                        + "'" + tfDiaChi.getText() + "',\n "
//                        + "'" + cbLaChungCu.getSelectedItem() + "',\n "
//                        + "'" + tfNgayLap.getText() + "'); ";
//                add = conn.prepareStatement(sql);
////                System.out.println(sql);
//                row = add.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Đã lưu thành công");
                conn.close();
                this.dispose();
            }
            catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Thông tin bạn điền có thể chưa chính xác.\n"
                        + "Có thể bạn đã nhập sai cú pháp ngày tháng phải là: yyyy-mm-dd.\n"
                        + "Hoặc là bạn đã điền sai thông tin của họ tên và số CMND của chủ hộ.\n"
                        + "Lưu ý, chủ hộ mới phải là một nhân khẩu trong hộ.");
            }
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa hộ khẩu này?\n"
                + "Nếu xóa, bạn sẽ xóa cả dữ liệu nhân khẩu của hộ!", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            try{
                 conn = Connector.getConnection();
                String sql = "UPDATE ho_khau "
                        + "SET deleted = 1\n "
                        + "WHERE ho_khau_id = " + hoKhau.getHoKhauId() + ";"; 
                PreparedStatement add = conn.prepareStatement(sql);
                System.out.println(sql);
                int row = add.executeUpdate();

                sql = "UPDATE nhan_khau "
                        + "SET deleted = 1\n "
                        + "WHERE so_ho_khau = '" + hoKhau.getSoHoKhau()+ "';"; 
                add = conn.prepareStatement(sql);
                System.out.println(sql);
                row = add.executeUpdate();
                
//                sql = "INSERT INTO ho_khau_log(ho_khau_id, so_ho_khau, chu_ho_id, chu_ho_CMND, dia_chi, la_chung_cu, ngay_lap) "
//                        + "VALUES ("
//                        + hoKhau.getHoKhauId()+  ",\n "
//                        + "'" + hoKhau.getSoHoKhau() + "',\n "
//                        + "(\n" +
//                        "    SELECT nhan_khau_id\n" +
//                        "    FROM nhan_khau\n" +
//                        "    WHERE so_CMND = '" + hoKhau.getChuHoCMND() + "'),\n "
//                        + "'" + hoKhau.getChuHoCMND() + "',\n "
//                        + "'" + hoKhau.getDiaChi() + "',\n "
//                        + "'" + hoKhau.getLaChungCu() + "',\n "
//                        + "'" + hoKhau.getNgayLap() + "'); ";
//                add = conn.prepareStatement(sql);
//                System.out.println(sql);
//                row = add.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Đã xóa thành công");
                conn.close();
                this.dispose();
            } catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu.");
            }
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThemNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNhanKhauActionPerformed

    private void btnHoanTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoanTacMouseClicked
        // TODO add your handling code here:
        displayTextFields();
    }//GEN-LAST:event_btnHoanTacMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemNhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNhanKhauMouseClicked
        // TODO add your handling code here:
        ThemNhanKhauForm newForm = new ThemNhanKhauForm(this.hoKhau);
        newForm.setVisible(true);
    }//GEN-LAST:event_btnThemNhanKhauMouseClicked

    private void PanelSuaXoaHoKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuaXoaHoKhauMouseClicked
        // TODO add your handling code here:
        displayNhanKhau();
    }//GEN-LAST:event_PanelSuaXoaHoKhauMouseClicked

    private void btnSuaNhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNhanKhauMouseClicked
        // TODO add your handling code here:
        // ------ kiểm tra xem đã chọn hộ khẩu chưa
        if (key.equals("") || nhanKhau == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhân khẩu trong bảng\n"
                    + "để theo dõi thêm thông tin về nhân khẩu đó.");
            return;
        }
        // ------ truyền vào form sửa hộ khẩu khẩu
        SuaXoaNhanKhauForm newForm =  new SuaXoaNhanKhauForm(nhanKhau);
        newForm.setVisible(true);
    }//GEN-LAST:event_btnSuaNhanKhauMouseClicked

    private void btnSuaNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhanKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaNhanKhauActionPerformed

    private void btnTachHoKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTachHoKhauMouseClicked
        // TODO add your handling code here:
        TachHoKhauForm newForm = new TachHoKhauForm(this.hoKhau);
        newForm.setVisible(true);
    }//GEN-LAST:event_btnTachHoKhauMouseClicked

    private void btnTachHoKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTachHoKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTachHoKhauActionPerformed

        // ------------- CONNECTION SQL PARAMETER---------------
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        Statement st = null;
    
    // ----------------- display bản ghi ----------------------
    private void displayTextFields() {
        try {
            tfSoHoKhau.setText(hoKhau.getSoHoKhau());
            tfDiaChi.setText(hoKhau.getDiaChi());
            tfNgayLap.setText(hoKhau.getNgayLap());
            tfSoCMND.setText(hoKhau.getChuHoCMND());
            cbLaChungCu.setSelectedItem(hoKhau.getLaChungCu());
            String hoTenChuHo = "";
            try {
                conn = Connector.getConnection();
                st = conn.createStatement();
                String keyCMND = hoKhau.getChuHoCMND();
                String sql = "SELECT ho_ten FROM nhan_khau WHERE so_CMND = \'" + keyCMND + "\';";
                Statement statement = conn.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);
                while (resultSet.next()){
                    hoTenChuHo = resultSet.getString("ho_ten");
                    tfTenChuHo.setText(hoTenChuHo);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // ---------------- display thông tin nhân khẩu của hộ --------
    private void displayNhanKhau(){
        try {
            conn = Connector.getConnection();
            st = conn.createStatement();
            String sql ="SELECT nhan_khau_id as 'ID', so_CMND as 'Số CMND', ho_ten as 'Họ và tên', gioi_tinh as 'Giới tính', ngay_sinh as 'Ngày sinh', nghe_nghiep as 'Nghề nghiệp', "
                    + "quan_he_voi_chu_ho as 'Quan hệ với chủ hộ', qua_doi as 'Qua đời' FROM nhan_khau"
                    + " WHERE so_ho_khau = \'" + hoKhau.getSoHoKhau() + "\' AND deleted = 0;";
            rs = st.executeQuery(sql);
            tNhanKhau.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu");

        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaXoaHoKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaXoaHoKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaXoaHoKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaXoaHoKhauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaXoaHoKhauForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSuaXoaHoKhau;
    private javax.swing.JButton btnHoanTac;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSuaNhanKhau;
    private javax.swing.JButton btnTachHoKhau;
    private javax.swing.JButton btnThemNhanKhau;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLaChungCu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tNhanKhau;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfNgayLap;
    private javax.swing.JTextField tfSoCMND;
    private javax.swing.JTextField tfSoHoKhau;
    private javax.swing.JTextField tfTenChuHo;
    // End of variables declaration//GEN-END:variables
}
