/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demographic.quanlythuphi;

//import com.sun.jdi.connect.spi.Connection;
import demographic.components.mainpage.*;
import demographic.components.suaxoaform.SuaXoaDongPhiForm;
import demographic.components.suaxoaform.SuaXoaKhoanPhiForm;
import demographic.components.themform.*;
import demographic.components.themform.ThemKhoanPhiForm;
import demographic.components.themform.ThemDongPhiForm;
import demographic.components.themform.ThemNhanKhauForm;
import demographic.quanlynhankhau.*;
import demographic.models.User;
import demographic.login.MainFormForAdmin;
import demographic.login.MainFormForUser;
import demographic.models.NhanKhau;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.JFileChooser;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author vietanh
 */
public class KhoanPhiMainPage extends javax.swing.JFrame {

    public User user;
    // ------------- CONNECTION SQL PARAMETER---------------
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    // ----------------- EXTRACT DATA FROM CLICK ON TABLE -----------------
    String key = "";

    /**
     * Creates new form NhanKhauMainPage
     */
    public KhoanPhiMainPage() {
        initComponents();
        displayDongPhi();
        displayKhoanPhi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        khoanPhiPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbHoKhau = new javax.swing.JLabel();
        lbNhanKhau = new javax.swing.JLabel();
        lbThoat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTimKhoanPhi = new javax.swing.JButton();
        btnSuaKhoanPhi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKhoanPhi = new javax.swing.JTable();
        btnTrinhBanGhiKhoanPhi = new javax.swing.JButton();
        btnXuatFileKhoanPhi = new javax.swing.JButton();
        tfTimKhoanPhi = new javax.swing.JTextField();
        btnThemKhoanPhi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDongPhi = new javax.swing.JTable();
        btnTrinhBanGhiDongPhi = new javax.swing.JButton();
        btnThemDongPhi = new javax.swing.JButton();
        btnSuaDongPhi = new javax.swing.JButton();
        btnXuatFileDongPhi = new javax.swing.JButton();
        btnTimDongPhi = new javax.swing.JButton();
        tfTimDongPhi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        khoanPhiPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        lbHoKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbHoKhau.setForeground(new java.awt.Color(255, 255, 255));
        lbHoKhau.setText("Đóng góp");
        lbHoKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDongGopMouseClicked(evt);
            }
        });

        lbNhanKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhanKhau.setForeground(new java.awt.Color(255, 255, 255));
        lbNhanKhau.setText("Đóng phí");
        lbNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IbDongPhiMouseClicked(evt);
            }
        });

        lbThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbThoat.setForeground(new java.awt.Color(255, 255, 255));
        lbThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThoat.setText("Thoát    ");
        lbThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNhanKhau)
                    .addComponent(lbHoKhau))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lbNhanKhau)
                .addGap(18, 18, 18)
                .addComponent(lbHoKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbThoat)
                .addGap(33, 33, 33))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUẢN LÝ KHOẢN PHÍ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnTimKhoanPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnTimKhoanPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKhoanPhi.setText("Tìm theo tên");
        btnTimKhoanPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKhoanPhiMouseClicked(evt);
            }
        });

        btnSuaKhoanPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnSuaKhoanPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaKhoanPhi.setText("Sửa");
        btnSuaKhoanPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaKhoanPhiMouseClicked(evt);
            }
        });

        tKhoanPhi.setForeground(new java.awt.Color(0, 102, 102));
        tKhoanPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tKhoanPhi.setGridColor(new java.awt.Color(188, 206, 206));
        tKhoanPhi.setRowHeight(26);
        tKhoanPhi.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tKhoanPhi.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tKhoanPhi.setShowGrid(true);
        tKhoanPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKhoanPhiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tKhoanPhi);

        btnTrinhBanGhiKhoanPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnTrinhBanGhiKhoanPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnTrinhBanGhiKhoanPhi.setText("Trình bản ghi");
        btnTrinhBanGhiKhoanPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrinhBanGhiKhoanPhiMouseClicked(evt);
            }
        });

        btnXuatFileKhoanPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnXuatFileKhoanPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFileKhoanPhi.setText("Xuất file");
        btnXuatFileKhoanPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatFileKhoanPhiMouseClicked(evt);
            }
        });

        tfTimKhoanPhi.setForeground(new java.awt.Color(0, 102, 102));
        tfTimKhoanPhi.setText("Nhâp tên");
        tfTimKhoanPhi.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tfTimKhoanPhi.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        tfTimKhoanPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKhoanPhiActionPerformed(evt);
            }
        });

        btnThemKhoanPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnThemKhoanPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKhoanPhi.setText("Thêm");
        btnThemKhoanPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemKhoanPhiMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHOẢN PHÍ");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐÓNG PHÍ");

        tDongPhi.setForeground(new java.awt.Color(0, 102, 102));
        tDongPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tDongPhi.setGridColor(new java.awt.Color(188, 206, 206));
        tDongPhi.setRowHeight(26);
        tDongPhi.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tDongPhi.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tDongPhi.setShowGrid(true);
        tDongPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDongPhiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tDongPhi);

        btnTrinhBanGhiDongPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnTrinhBanGhiDongPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnTrinhBanGhiDongPhi.setText("Trình bản ghi");
        btnTrinhBanGhiDongPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrinhBanGhiDongPhiMouseClicked(evt);
            }
        });

        btnThemDongPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnThemDongPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDongPhi.setText("Thêm");
        btnThemDongPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemDongPhiMouseClicked(evt);
            }
        });

        btnSuaDongPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnSuaDongPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaDongPhi.setText("Sửa");
        btnSuaDongPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaDongPhiMouseClicked(evt);
            }
        });

        btnXuatFileDongPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnXuatFileDongPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFileDongPhi.setText("Xuất file");
        btnXuatFileDongPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatFileDongPhiMouseClicked(evt);
            }
        });

        btnTimDongPhi.setBackground(new java.awt.Color(0, 51, 51));
        btnTimDongPhi.setForeground(new java.awt.Color(255, 255, 255));
        btnTimDongPhi.setText("Tìm theo số hộ khẩu");
        btnTimDongPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimDongPhiMouseClicked(evt);
            }
        });

        tfTimDongPhi.setForeground(new java.awt.Color(0, 102, 102));
        tfTimDongPhi.setText("Nhập số hộ khẩu");
        tfTimDongPhi.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tfTimDongPhi.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        tfTimDongPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimDongPhiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout khoanPhiPanelLayout = new javax.swing.GroupLayout(khoanPhiPanel);
        khoanPhiPanel.setLayout(khoanPhiPanelLayout);
        khoanPhiPanelLayout.setHorizontalGroup(
            khoanPhiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoanPhiPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(khoanPhiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(khoanPhiPanelLayout.createSequentialGroup()
                        .addGroup(khoanPhiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(khoanPhiPanelLayout.createSequentialGroup()
                                .addComponent(btnTrinhBanGhiKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuaKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXuatFileKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                                .addComponent(btnTimKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfTimKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(khoanPhiPanelLayout.createSequentialGroup()
                        .addComponent(btnTrinhBanGhiDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThemDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXuatFileDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfTimDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        khoanPhiPanelLayout.setVerticalGroup(
            khoanPhiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(khoanPhiPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(khoanPhiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrinhBanGhiKhoanPhi)
                    .addComponent(btnSuaKhoanPhi)
                    .addComponent(btnXuatFileKhoanPhi)
                    .addComponent(btnTimKhoanPhi)
                    .addComponent(tfTimKhoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemKhoanPhi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(khoanPhiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrinhBanGhiDongPhi)
                    .addComponent(btnSuaDongPhi)
                    .addComponent(btnXuatFileDongPhi)
                    .addComponent(btnTimDongPhi)
                    .addComponent(tfTimDongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemDongPhi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khoanPhiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khoanPhiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ----------------- EXCEL EXTRACTION -------------------------------
    private void btnXuatFileKhoanPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatFileKhoanPhiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatFileKhoanPhiMouseClicked

    private void btnTrinhBanGhiKhoanPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrinhBanGhiKhoanPhiMouseClicked
        // TODO add your handling code here:
        displayKhoanPhi();
    }//GEN-LAST:event_btnTrinhBanGhiKhoanPhiMouseClicked

    private void tKhoanPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKhoanPhiMouseClicked

    }//GEN-LAST:event_tKhoanPhiMouseClicked

    // -------------------------- EDIT DATA --------------------------------
    private void btnSuaKhoanPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaKhoanPhiMouseClicked
        // TODO add your handling code here:
        SuaXoaKhoanPhiForm newForm = new SuaXoaKhoanPhiForm();
        newForm.setVisible(true);
    }//GEN-LAST:event_btnSuaKhoanPhiMouseClicked

    private void btnTimKhoanPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKhoanPhiMouseClicked
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quan_ly_khu_dan_cu", "root", "");
            st = conn.createStatement();
            String tenKhoanPhi = tfTimKhoanPhi.getText();
            String sqlQuery = "SELECT id_khoan_thu_phi AS 'ID Khoản Phí',"
                    + "ten_khoan_thu_phi AS 'Tên Khoản Phí',"
                    + "tien_phi AS 'Tiền Phí',"
                    + "ngay_bat_dau AS 'Ngày Bắt Đầu',"
                    + "ngay_ket_thuc AS 'Ngày kết thúc',"
                    + "chi_tiet AS 'Chi tiết'"
                    + "FROM `khoan_thu_phi` "
                    + "WHERE `ten_khoan_thu_phi` LIKE " + "'%" + tenKhoanPhi + "%' ";
            rs = st.executeQuery(sqlQuery);
            tKhoanPhi.setModel(DbUtils.resultSetToTableModel(rs));
            tfTimKhoanPhi.setText("Nhập tên");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu");
        }
    }//GEN-LAST:event_btnTimKhoanPhiMouseClicked

    // -------------------- BACK TO MAIN FORM ----------------------------
    private void lbThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThoatMouseClicked
        // TODO add your handling code here:
        if (user.isAdmin == 1) {
            MainFormForAdmin mainForm = new MainFormForAdmin();
            mainForm.setVisible(true);
            mainForm.user = user;
            this.dispose();
        } else if (user.isAdmin == 0) {
            MainFormForUser mainForm = new MainFormForUser();
            mainForm.setVisible(true);
            mainForm.user = user;
            this.dispose();
        } else {
            MainFormForUser mainForm = new MainFormForUser();
            mainForm.setVisible(true);
            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_lbThoatMouseClicked

    private void IbDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IbDongPhiMouseClicked
        // TODO add your handling code here:
        KhoanPhiMainPage newFrame = new KhoanPhiMainPage();
        newFrame.setVisible(true);
        newFrame.user = user;
        this.dispose();
    }//GEN-LAST:event_IbDongPhiMouseClicked

    private void lbDongGopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDongGopMouseClicked
        // TODO add your handling code here:
        KhoanDongGopMainPage newFrame = new KhoanDongGopMainPage();
        newFrame.setVisible(true);
        newFrame.user = user;
        this.dispose();
    }//GEN-LAST:event_lbDongGopMouseClicked

    private void btnThemKhoanPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemKhoanPhiMouseClicked
        // TODO add your handling code here:
        ThemKhoanPhiForm newForm = new ThemKhoanPhiForm();
        newForm.setVisible(true);
    }//GEN-LAST:event_btnThemKhoanPhiMouseClicked

    private void tfTimKhoanPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKhoanPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKhoanPhiActionPerformed

    private void tDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDongPhiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tDongPhiMouseClicked

    private void btnTrinhBanGhiDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrinhBanGhiDongPhiMouseClicked
        // TODO add your handling code here:
        displayDongPhi();
    }//GEN-LAST:event_btnTrinhBanGhiDongPhiMouseClicked

    private void btnThemDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemDongPhiMouseClicked
        // TODO add your handling code here:
        ThemDongPhiForm newForm = new ThemDongPhiForm();
        newForm.setVisible(true);
    }//GEN-LAST:event_btnThemDongPhiMouseClicked

    private void btnSuaDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaDongPhiMouseClicked
        // TODO add your handling code here:
        SuaXoaDongPhiForm newForm = new SuaXoaDongPhiForm();
        newForm.setVisible(true);
    }//GEN-LAST:event_btnSuaDongPhiMouseClicked

    private void btnXuatFileDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatFileDongPhiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatFileDongPhiMouseClicked

    private void btnTimDongPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimDongPhiMouseClicked
        // TODO add your handling code here:'
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quan_ly_khu_dan_cu", "root", "");
            st = conn.createStatement();
            String soHoKhau = tfTimDongPhi.getText();
            String sqlQuery = "SELECT "
                    + "id_dong_phi AS 'ID Đóng Phí',"
                    + "id_khoan_thu_phi AS 'ID Khoản Thu Phí',"
                    + "so_ho_khau AS 'Số hộ khẩu',"
                    + "so_tien AS 'Số tiền',"
                    + "da_dong AS 'Đã đóng',"
                    + "ngay_dong AS 'Ngày đóng'"
                    + "FROM `dong_phi` "
                    + "WHERE `so_ho_khau` LIKE " + "'%" + soHoKhau + "%' ";
            rs = st.executeQuery(sqlQuery);
            tDongPhi.setModel(DbUtils.resultSetToTableModel(rs));
            tfTimDongPhi.setText("Nhập tên");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu");
        }
    }//GEN-LAST:event_btnTimDongPhiMouseClicked

    private void tfTimDongPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimDongPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimDongPhiActionPerformed

    private void displayKhoanPhi() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quan_ly_khu_dan_cu", "root", "");
            st = conn.createStatement();
            String sql = "SELECT id_khoan_thu_phi AS 'ID Khoản Phí',"
                    + "ten_khoan_thu_phi AS 'Tên Khoản Phí',"
                    + "tien_phi AS 'Tiền Phí',"
                    + "ngay_bat_dau AS 'Ngày Bắt Đầu',"
                    + "ngay_ket_thuc AS 'Ngày kết thúc',"
                    + "chi_tiet AS 'Chi tiết'"
                    + "FROM khoan_thu_phi";
            rs = st.executeQuery(sql);
            tKhoanPhi.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: Không đọc được khoan_thu_phi");

        }
    }

    private void displayDongPhi() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quan_ly_khu_dan_cu", "root", "");
            st = conn.createStatement();
            String sql = "SELECT "
                    + "id_dong_phi AS 'ID Đóng Phí',"
                    + "id_khoan_thu_phi AS 'ID Khoản Thu Phí',"
                    + "so_ho_khau AS 'Số hộ khẩu',"
                    + "so_tien AS 'Số tiền',"
                    + "da_dong AS 'Đã đóng',"
                    + "ngay_dong AS 'Ngày đóng'"
                    + " FROM dong_phi";
            rs = st.executeQuery(sql);
            tDongPhi.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: Không đọc được dong_phi");
        }
    }

    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoanPhiMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoanPhiMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoanPhiMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoanPhiMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoanPhiMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaDongPhi;
    private javax.swing.JButton btnSuaKhoanPhi;
    private javax.swing.JButton btnThemDongPhi;
    private javax.swing.JButton btnThemKhoanPhi;
    private javax.swing.JButton btnTimDongPhi;
    private javax.swing.JButton btnTimKhoanPhi;
    private javax.swing.JButton btnTrinhBanGhiDongPhi;
    private javax.swing.JButton btnTrinhBanGhiKhoanPhi;
    private javax.swing.JButton btnXuatFileDongPhi;
    private javax.swing.JButton btnXuatFileKhoanPhi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel khoanPhiPanel;
    private javax.swing.JLabel lbHoKhau;
    private javax.swing.JLabel lbNhanKhau;
    private javax.swing.JLabel lbThoat;
    private javax.swing.JTable tDongPhi;
    private javax.swing.JTable tKhoanPhi;
    private javax.swing.JTextField tfTimDongPhi;
    private javax.swing.JTextField tfTimKhoanPhi;
    // End of variables declaration//GEN-END:variables
}
